---
id: fukuoka-ruby-award-7
base_name: mruby-embedded-groonga
tags:
- rabbit
- mruby
- groonga
- full-text-search
presentation_date: 2015-01-23
version: 2015.01.23.2
licenses:
- CC BY-SA 4.0
slideshare_id: fukuoka-ruby-award-7
speaker_deck_id: quan-wen-jian-suo-enzingroongahefalsemrubyfalsezu-miip-mi
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: Kouhei Sutou
  email: kou@clear-code.com
  rubygems_user: kou
  slideshare_user: kou
  speaker_deck_user: kou
